language: node_js
node_js:
  - '16'

before_install:
  - openssl aes-256-cbc -K $encrypted_key -iv $encrypted_iv -in deploy_key.enc -out ~/.ssh/id_rsa -d
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa


before_cache:
  - npm cache clean --force

install:
  - npm install

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ssh -o StrictHostKeyChecking=no joy@ec2-3-87-42-90.compute-1.amazonaws.com "cd calendar/Calendar && git pull && npm install && pm2 restart server.js"

on:
  branch: main

