language: node_js
node_js:
  - '16'

before_install:
  - echo -e "Host ec2-3-87-42-90.compute-1.amazonaws.com\n\tStrictHostKeyChecking no\n" >> ~/.ssh/config
  - echo "$SSH_PRIVATE_KEY" | base64 --decode > ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - eval "$(ssh-agent -s)"
  - ssh-add ~/.ssh/id_rsa

install:
  - cd ./server
  - npm install

script: 'true'

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ssh -o StrictHostKeyChecking=no joy@ec2-3-87-42-90.compute-1.amazonaws.com "cd calendar/Calendar/server && git pull && npm install && npm start"

on:
  branch:
    - main


