language: node_js
node_js:
  - '16'

before_install:
  # Install SSH agent
  - eval "$(ssh-agent -s)"
  # Add your SSH key to the agent
  - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -

before_cache:
  - npm cache clean --force

install:
  - npm install

script:
  - npm test

deploy:
  provider: script
  skip_cleanup: true
  script:
    - ssh -o StrictHostKeyChecking=no joy@ec2-3-87-42-90.compute-1.amazonaws.com "cd calendar/Calendar && git pull && npm install && pm2 restart server.js"

on:
  branch: main

